export const ictTechSkills = [
    "Networking",
    "Cybersecurity",
    "Cloud Computing",
    "Data Analysis",
    "Database Management",
    "System Administration",
    "Virtualization",
    "IT Support",
    "Big Data",
    "Business Intelligence",
    "Artificial Intelligence",
    "Machine Learning",
    "Internet of Things (IoT)",
    "Blockchain",
    "Digital Marketing",
    "Web Development",
    "Software Development",
    "Mobile App Development",
    "IT Project Management",
    "UI/UX Design",
    "Content Management Systems (CMS)",
    "Enterprise Resource Planning (ERP)",
    "Customer Relationship Management (CRM)",
    "VoIP (Voice over Internet Protocol)",
    "IT Consulting",
    "Data Warehousing",
    "Information Security",
    "IT Governance",
    "Telecommunications",
    "Wireless Technologies",
    "IT Strategy",
    "Robotics",
    "Embedded Systems",
    "Operating Systems",
    "DevOps",
    "Business Analysis",
    "Quality Assurance (QA)",
    "ITIL (Information Technology Infrastructure Library)",
    "Network Security",
    "Disaster Recovery",
    "IT Compliance",
    "Digital Forensics",
    "Cloud Security",
    "Risk Management",
    "Data Mining",
    "Computer Vision",
    "Natural Language Processing",
    "Systems Integration",
    "UX Research",
    "E-commerce Platforms",
    "Data Visualization",
    "Information Architecture",
    "Front-end Development",
    "Back-end Development",
    "Database Management",
    "API Development",
    "Version Control",
    "Testing and Debugging",
    "Deployment and DevOps",
    "Security",
    "Agile Methodologies",
    "Problem Solving and Adaptability"
  ];
  